### ISSUE TITLE
Incomplete plugin download

### ISSUE THREAD

**Issue by mtrolley** [rrgeorge/vim-blink#5]
Thanks for this by the way, it's great to be able to use plugins in Blink.

I've installed the Airline plugins like so:
```vim
Blink 'vim-airline/vim-airline'
Blink 'vim-airline/vim-airline-themes'
```

`:BlinkUpdate` tells me all plugins are up to date. However, it looks like the `vim-airline-themes` plugin didn't completely install. In `~/.vim/pack/blink/opt/vim-airline_vim-airline-themes/autoload/airline/themes` I only have 5 files, where as the same plugin installed with `vim-plug` on my Mac as 232. I found this because trying to set my Airline theme gives an error that the theme can't be found.

Do you have any suggestion on debugging why the plugin didn't install completely?

**Comment by rrgeorge** [comment]
I’ve seen this happen randomly but I usually just wipe the `.vim/pack/blink` directory and let it redownload and reinstall it. I think that maybe sometimes the tgz from GitHub is corrupt or incomplete..

**Comment by mtrolley** [comment]
Will try that, thanks.

**Comment by rrgeorge** [comment]
> `:BlinkUpdate` tells me all plugins are up to date. However, it looks like the `vim-airline-themes` plugin didn't completely install. In `~/.vim/pack/blink/opt/vim-airline_vim-airline-themes/autoload/airline/themes` I only have 5 files, where as the same plugin installed with `vim-plug` on my Mac as 232. I found this because trying to set my Airline theme gives an error that the theme can't be found.

Keep in mind that on your Mac with plug, it’s using git as the backend, so all those git objects will not be present in blink
